---
services:
  bank:
    container_name: bank-container
    build: ./bank/
    ports:
      - "1111:80"
  creditcard:
    container_name: credit-cont
    build: ./creditcard/
    ports:
      - "1112:80"
  debitcard:
    container_name: debit-cont
    build: ./debitcard/
    ports:
      - "1113:80"
  database:
    container_name: database-cont
    build: ./database/
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
